name: Daily Email Automation

on:
  schedule:
    - cron: "0 10 28 8 *"   # 3:30 PM IST (10:00 UTC)
    - cron: "0 11 28 8 *"   # 4:30 PM IST (11:00 UTC)
    - cron: "0 12 28 8 *"   # 5:30 PM IST (12:00 UTC)
  workflow_dispatch:


jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TOKEN_PICKLE: ${{ secrets.TOKEN_PICKLE }}
        run: python main.py
